// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toner.Infrastructure.Persistence;

#nullable disable

namespace Toner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TonerDbContext))]
    [Migration("20260927165942_AddTechnicianAssets")]
    partial class AddTechnicianAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toner.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("AssetModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentClientLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetModelId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CurrentClientLocationId");

                    b.HasIndex("LifecycleStatus");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetBrands", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetBrandId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsumablesPrintThreshold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GeneralMonthsInterval")
                        .HasColumnType("integer");

                    b.Property<int>("GeneralPrintThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UnitsMonthsInterval")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsPrintThreshold")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetBrandId", "Name")
                        .IsUnique();

                    b.ToTable("AssetModels", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetStatusLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ClientId");

                    b.ToTable("AssetStatusLogs", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MaintenanceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ServiceTicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MaintenanceOrderId");

                    b.HasIndex("ServiceTicketId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("AssignmentHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssignmentHistories_ExactlyOneTarget", "(\"ServiceTicketId\" IS NOT NULL) <> (\"MaintenanceOrderId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Toner.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name", "StateOrProvince")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsContractClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.ClientLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientLocations", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IncludedPrintsPerMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PricePerExtraPage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.ContractAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractAssets", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("MaintenanceOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceTicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceOrderId");

                    b.HasIndex("ServiceTicketId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Evidences", null, t =>
                        {
                            t.HasCheckConstraint("CK_Evidences_ExactlyOneTarget", "(\"ServiceTicketId\" IS NOT NULL) <> (\"MaintenanceOrderId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Toner.Domain.Entities.ExceptionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ExceptionLogs", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.MaintenanceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludesConsumables")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesGeneral")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesUnits")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaintenanceScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompletedAt")
                        .HasFilter("\"CompletedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MaintenanceScheduleId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("MaintenanceOrders", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.MaintenanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastConsumablesChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastConsumablesChangeCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastGeneralMaintenanceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastGeneralMaintenanceCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUnitsMaintenanceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastUnitsMaintenanceCounter")
                        .HasColumnType("bigint");

                    b.Property<long>("NextConsumablesDueCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NextGeneralDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NextGeneralDueCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NextUnitsDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NextUnitsDueCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractId");

                    b.ToTable("MaintenanceSchedules", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<long>("CounterValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("AssetId", "ReadingDate");

                    b.ToTable("MeterReadings", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.ServiceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalAssetBrand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ExternalAssetCounter")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalAssetModel")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientLocationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ResolvedAt")
                        .HasFilter("\"ResolvedAt\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("TechnicianId");

                    b.ToTable("ServiceTickets", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Technicians", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.TechnicianAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TechnicianId", "AssetId")
                        .IsUnique();

                    b.ToTable("TechnicianAssets", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.TechnicianAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechnicianAvailabilities", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.TechnicianCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TechnicianId", "CityId")
                        .IsUnique();

                    b.ToTable("TechnicianCoverages", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.TimeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MaintenanceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ServiceTicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasFilter("\"EndTime\" IS NULL");

                    b.HasIndex("ClientId");

                    b.HasIndex("MaintenanceOrderId");

                    b.HasIndex("ServiceTicketId");

                    b.HasIndex("StartTime");

                    b.HasIndex("TechnicianId");

                    b.HasIndex(new[] { "TechnicianId" }, "IX_TimeLogs_TechnicianId_Open")
                        .HasFilter("\"EndTime\" IS NULL");

                    b.ToTable("TimeLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimeLogs_ExactlyOneTarget", "(CASE WHEN \"ServiceTicketId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"MaintenanceOrderId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"AssetId\" IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("Toner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecurityStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Toner.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Toner.Domain.Entities.AssetModel", "AssetModel")
                        .WithMany("Assets")
                        .HasForeignKey("AssetModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.ClientLocation", "CurrentClientLocation")
                        .WithMany("Assets")
                        .HasForeignKey("CurrentClientLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssetModel");

                    b.Navigation("CurrentClientLocation");
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetModel", b =>
                {
                    b.HasOne("Toner.Domain.Entities.AssetBrand", "AssetBrand")
                        .WithMany("Models")
                        .HasForeignKey("AssetBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetBrand");
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetStatusLog", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("StatusLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssignmentHistory", b =>
                {
                    b.HasOne("Toner.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.MaintenanceOrder", "MaintenanceOrder")
                        .WithMany("AssignmentHistories")
                        .HasForeignKey("MaintenanceOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.ServiceTicket", "ServiceTicket")
                        .WithMany("AssignmentHistories")
                        .HasForeignKey("ServiceTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByUser");

                    b.Navigation("MaintenanceOrder");

                    b.Navigation("ServiceTicket");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.ClientLocation", b =>
                {
                    b.HasOne("Toner.Domain.Entities.City", "City")
                        .WithMany("ClientLocations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Client", "Client")
                        .WithMany("Locations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Toner.Domain.Entities.ContractAsset", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("ContractAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Contract", "Contract")
                        .WithMany("ContractAssets")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("Toner.Domain.Entities.MaintenanceOrder", "MaintenanceOrder")
                        .WithMany("Evidences")
                        .HasForeignKey("MaintenanceOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.ServiceTicket", "ServiceTicket")
                        .WithMany("Evidences")
                        .HasForeignKey("ServiceTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceOrder");

                    b.Navigation("ServiceTicket");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Toner.Domain.Entities.MaintenanceOrder", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.MaintenanceSchedule", "MaintenanceSchedule")
                        .WithMany("MaintenanceOrders")
                        .HasForeignKey("MaintenanceScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany("AssignedMaintenanceOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("MaintenanceSchedule");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.MaintenanceSchedule", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Contract", "Contract")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Toner.Domain.Entities.MeterReading", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("MeterReadings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("RegisteredByUser");
                });

            modelBuilder.Entity("Toner.Domain.Entities.ServiceTicket", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.ClientLocation", "ClientLocation")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("ClientLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("ClientLocation");

                    b.Navigation("ReportedByUser");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Technician", b =>
                {
                    b.HasOne("Toner.Domain.Entities.User", "User")
                        .WithOne("Technician")
                        .HasForeignKey("Toner.Domain.Entities.Technician", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toner.Domain.Entities.TechnicianAsset", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("TechnicianAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany("LinkedAssets")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.TechnicianAvailability", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany("AvailabilityHistory")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.TechnicianCoverage", b =>
                {
                    b.HasOne("Toner.Domain.Entities.City", "City")
                        .WithMany("TechnicianCoverages")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany("Coverages")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.TimeLog", b =>
                {
                    b.HasOne("Toner.Domain.Entities.Asset", "Asset")
                        .WithMany("TimeLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.MaintenanceOrder", "MaintenanceOrder")
                        .WithMany("TimeLogs")
                        .HasForeignKey("MaintenanceOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.ServiceTicket", "ServiceTicket")
                        .WithMany("TimeLogs")
                        .HasForeignKey("ServiceTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.Technician", "Technician")
                        .WithMany("TimeLogs")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("MaintenanceOrder");

                    b.Navigation("ServiceTicket");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Toner.Domain.Entities.User", b =>
                {
                    b.HasOne("Toner.Domain.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.Client", "Client")
                        .WithMany("Users")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Toner.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Client");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Asset", b =>
                {
                    b.Navigation("ContractAssets");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("MeterReadings");

                    b.Navigation("ServiceTickets");

                    b.Navigation("StatusLogs");

                    b.Navigation("TechnicianAssets");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Toner.Domain.Entities.AssetModel", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Toner.Domain.Entities.City", b =>
                {
                    b.Navigation("ClientLocations");

                    b.Navigation("TechnicianCoverages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Locations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Toner.Domain.Entities.ClientLocation", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ServiceTickets");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Contract", b =>
                {
                    b.Navigation("ContractAssets");

                    b.Navigation("MaintenanceSchedules");
                });

            modelBuilder.Entity("Toner.Domain.Entities.MaintenanceOrder", b =>
                {
                    b.Navigation("AssignmentHistories");

                    b.Navigation("Evidences");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Toner.Domain.Entities.MaintenanceSchedule", b =>
                {
                    b.Navigation("MaintenanceOrders");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Toner.Domain.Entities.ServiceTicket", b =>
                {
                    b.Navigation("AssignmentHistories");

                    b.Navigation("Evidences");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Toner.Domain.Entities.Technician", b =>
                {
                    b.Navigation("AssignedMaintenanceOrders");

                    b.Navigation("AssignedTickets");

                    b.Navigation("AvailabilityHistory");

                    b.Navigation("Coverages");

                    b.Navigation("LinkedAssets");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Toner.Domain.Entities.User", b =>
                {
                    b.Navigation("Technician");
                });
#pragma warning restore 612, 618
        }
    }
}
